title: C'est La Vie

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Chongqing

# Not everything is a post or a page. Maybe you want to document the various methods 
# in your open source project, members of a team, or talks at a conference. 
# Collections allow you to define a new type of document that behave like 
#  Pages or Posts do normally, but also have their own unique properties and namespace.
collections:
    arxiv:
        output: true
        permalink: /project/arxiv/:title.html
        layout: arxiv
#        permalink: /project/:title.html

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Keybase
include:
  - .well-known

# White-listed plugins
gems:
  - jekyll-sitemap

# Disqus System
disqus_shortname: iamquantumman
